config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#top'
  get 'home/about'

   resources :users do
    member do
      get :following, :followers
    end
  end

  resources :books,only: [:new, :create, :index, :show, :destroy,:edit,:update] do
  resource :favorites, only:[:new,:create,:destroy]
  resource :book_comments, only:[:create, :destroy]
  end	
  resources :users,only: [:show,:index,:edit,:update]
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user, optional: true
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
	def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book
	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
	validates :followed_id, presence: true
	validates :follower_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  has_many :books,dependent: :destroy
  has_many :book_comment, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key:"follower_id",
                                  dependent: :destroy
  has_many :passive_relationships, class_name:"Relationship",
                                  foreign_key:"followed_id",
                                  dependent: :destroy
  has_many :following,through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

def follow(other_user)
  following << other_user
end
def unfollow(other_user)
  active_relationships.find_by(followed_id: other_user.id).destroy
end
def following?(other_user)
  following.include?(other_user)
end

  attachment :profile_image, destroy: false

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :name, presence: true
  validates :introduction, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!, only: [:root_path]
	before_action :configure_permitted_parameters, if: :devise_controller?
	#デバイス機能実行前にconfigure_permitted_parametersの実行をする。
	protect_from_forgery with: :exception

  protected
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  #sign_out後のredirect先変更する。rootパスへ。rootパスはhome topを設定済み。
  def after_sign_out_path_for(resource)
    root_path(resource)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password ,:password_confirmation])
    #sign_upの際にnameのデータ操作を許。追加したカラム。
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
	before_action :baria_comment, only: [:destroy]

	def create
		book = Book.find(params[:book_id])
		if comment = current_user.book_comment.new(book_comment_params)
			comment.book_id = book.id
			comment.save
			redirect_to book_path(book)
		else
			render 'show'
		end
	end
	def destroy
		book = Book.find(params[:book_id])
		comment = current_user.book_comment.find_by(params[:comment])
		comment.destroy
		redirect_to book_path(book)
	end
	private
	def book_comment_params
		params.require(:book_comment).permit(:comment, :book_id, :user_id)
	end
	def baria_comment
  	unless params[:id].to_i == current_user.id
  		redirect_back(fallback_location: books_path)
  	end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :login_check, only: [:index, :new, :show,:edit, :update, :destroy]
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  
  def index
    @book = Book.new
    @books = Favorite.all
  	@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
    @users = User.all
    @book_comment = BookComment.new
  end
  def show
     @book = Book.new
    @book2 = Book.find(params[:id])
    @user = User.find(@book2.user_id)
    @book_comment = BookComment.new
  end

  def create
  	@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
    @book.user_id = current_user.id
  	if @book.save #入力されたデータをdbに保存する。
  		redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@books = Book.all
  		render 'index'
  	end
  end

  def edit
  	@book = Book.find(params[:id])
  end



  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
  	params.require(:book).permit(:title,:body)
  end
  def login_check
  unless user_signed_in?
    flash[:alert] = "ログインしてください"
    redirect_to "/users/sign_in"
  end
  end
  def ensure_correct_user
      @book = Book.find(params[:id])
      redirect_to(books_path) unless @book.user_id == current_user.id
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.new(book_id: book.id)
		favorite.save
		 redirect_back(fallback_location: books_path)
	end
	def destroy
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.find_by(book_id: book.id)
		favorite.destroy
		redirect_back(fallback_location: books_path)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_back(fallback_location: users_path)
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    redirect_back(fallback_location: users_path)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_check, only: [:index, :new, :show, :edit, :update, :destroy,:following, :followers]
	before_action :baria_user, only: [:update, :edit, :destroy]

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  def index
  	@users = User.all#一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end
  def show
      @book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
      @user = User.find(params[:id])
      @books = @user.books.page(params[:page]).reverse_order
  end
  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user.id), notice: "successfully updated user!"
  	else
  		render "edit"
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end
  def login_check
    unless user_signed_in?
    flash[:alert] = "ログインしてください"
    redirect_to "/users/sign_in"
    end
  end
  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_newform.html.erb
<%= form_for(@book) do |f| %>
 <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <%@book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>

<%= render "books/newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to "/users/#{book.user.id}" do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<td style="text-align: center;">
						<div class="glyphicon glyphicon-comment"></div>
						<a href="#comments"><%= book.book_comments.count %></a>
					</td>
					<td style="text-align: center;">
					     <% if book.favorited_by?(current_user)%>
							<%= link_to book_favorites_path(book), method: :delete do %>
							<div class= "glyphicon glyphicon-heart" area-hidden = "true" style ="color :red;" ></div>
							<%= book.favorites.count %> いいね
							<% end %>
						
						<div style="text-align: center;">
							<% else %>
							<%= link_to book_favorites_path(book), method: :post do %>
							<div class="glyphicon glyphicon-heart" aria-hidden = "true"></div>
							<%= book.favorites.count %> いいね
							<% end %>
						<% end %>
						</div>
					</td>
					<td colspan="6"></td>
				</tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>
		<% unless  @user.id == current_user.id  %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "フォロー外す", class: "btn btn-primary" %>
<% end %>
  <% else %>
    <%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォローする", class: "btn btn-primary" %>
<% end %>
  <% end %>
  </div>
<% end %>

		<h2>New book</h2>
		<%= render 'books/newform' %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to user_path(@user.id) do %>
						<%= attachment_image_tag(@user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @user.name %>
						<% end %>
					</td>
					<td><%= link_to @book2.title,book_path(@book2.id)%></td>
					<td><%= @book2.body %></td>

					<% if @user.id == current_user.id %>
					<td><%= link_to "Edit", "/books/#{@book2.id}/edit", class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td><%= link_to "Destroy",book_path, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger" %></td>
					<% end %>

						<td style="text-align:center;">
					     <% if @book2.favorited_by?(current_user)%>
							<%= link_to book_favorites_path(@book2), method: :delete do %>
							<div class= "glyphicon glyphicon-heart" area-hidden = "true" style ="color :red;" ></div>
							<%= @book2.favorites.count %> いいね
							<% end %>
						
						
							<% else %>
							<%= link_to book_favorites_path(@book2), method: :post do %>
							<div class="glyphicon glyphicon-heart" aria-hidden = "true"></div>
							<%= @book2.favorites.count %> いいね
							<% end %>
						<% end %>
					</td>
					<td>
						<div class="glyphicon glyphicon-comment"></div>
						<a href="#comments"><%= @book2.book_comments.count %></a>
					</td>
				</tr>
				<tr>
					<td>
					<div class="comment-list bt style-2" id ="comments">
						<div class="float-wrapper">
							<h2 class="comment-count"><%= @book2.book_comments.count %>件コメント</h2>
						</div>
					</div>
				</td>
				<td colspan="4"></td>
				</tr>

				<%@book2.book_comments.each do |book_comment|%>
					<tr class="comment">
						<td>
						<div class ="comment-body bb">
							<div class="commnet-avatar">
								<div class="avatar">
									<%= attachment_image_tag(book_comment.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
								</div>
							</div>
							<div class="comment-text">
								<div class="comment-author clearfix">
									<a href="#" class="link-author"><%=book_comment.user.name %></a>
									<span class="comment-meta">
										<span class="comment-date"><%= book_comment.created_at.strftime('%Y/%m/%d')%></span>
									</span>
								</div>
								<div class="comment-entry"><%= book_comment.comment%></div>
							</div>
							</div>
						</td>
						<td colspan="4"></td>
						<td><%= link_to book_book_comments_path(@book2), method: :delete do %>
							<div class= "glyphicon glyphicon-trash" area-hidden = "true"></div>
							<% end %>
						</td>
						
					</tr>
					<% end %>
					<tr>
						<td>
							<%= form_for [@book2, @book_comment] do |f| %>
    						<div class="row">
       							<div class="col-sm-12">
            						<%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
       							</div>
   							</div>
    							<%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
							<% end %>
						</td>
						<td colspan="4"></td>
					</tr>



			</table>

	</div>
</div>

app/views/home/about.html.erb
<h1>welcome to<span class="glyphicon glyphicon-book"></span>
<strong>Bookers</strong>  !!</h1>

app/views/home/top.html.erb
<div class="row">
	<div class="main col-md-offset-3 col-md-6">
		<h1>welcome to<span class="glyphicon glyphicon-book"></span>
			<strong>Bookers</strong>  !!</h1>
			<p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,</p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about varioius books!</p>

			<div class="btn-wrapper">
				<div class="row">
					<p><%=link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
				</div>
				<div class="row">
					<p><%=link_to "Sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
				</div>
			</div>

	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--ヘッダーの記述-->
    <<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">

        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <!--if文でサインインとアウト時の表示を変更-->
            <% if user_signed_in? %>
            <li><%= link_to ' home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' users', users_path, class: 'glyphicon glyphicon-user users' %></li>
            <li><%= link_to ' books', books_path, class: 'glyphicon glyphicon-book books' %></li>
            <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
            <% else %>
            <li><%= link_to ' home', root_path, class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' about', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
            <li><%= link_to ' sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
            <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></li>
            <% end %>
          </ul>
        </nav>

      </div>
    </header>
    <!--ヘッダーの記述-->
    <div class="container">
      <p id="notice"><%= notice %></p> <!--デバイスでnotice設定されているので呼び出してるだけ-->

    <%= yield %>
  </div>
  </body>
</html>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");
$("#followers").html('<%= @user.followers.count %>');

app/views/relationships/dstroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");
$("#followers").html('<%= @user.followers.count %>');

app/views/relationships/follows.html.erb
<h2>Follows Users</h2>

<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
			<td><%= user.name%></td>
			<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>






			<td style="text-align: center;">
				
				<p>フォロワー数<%= user.relationships.count %></p>
			</td>
			<td style="text-align: center;">
				
				<p>フォロ-数<%= user.relationships.count %></p>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/relationships/follwers.html.erb
<h2>Followers User</h2>

<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
			<td><%= user.name%></td>
			<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>






			<td style="text-align: center;">
				
				<p>フォロワー数<%= user.relationships.count %></p>
			</td>
			<td style="text-align: center;">
				
				<p>フォロ-数<%= user.relationships.count %></p>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/users/_profile.html.erb
<table class="table">
		<tr><%= attachment_image_tag(user, :profile_image , :fill, 100, 100, fallback: "no_image.jpg") %></tr>

		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>
		<tr>
			<% @user ||= current_user %>
		<div class="stats">
			<th>follow</th>
			<th><a href="<%= following_user_path(@user) %>">
    				<strong id="following" class="stat">
      					<%= @user.following.count %>
    				</strong>
  				</a>
  			</th>
  			</tr>
  			<tr>
  				<th>followers</th>
			<th><a href="<%= followers_user_path(@user) %>">
    				<strong id="followers" class="stat">
      					<%= @user.followers.count %>
    				</strong>
  				</a></th>
  		</div>
			</tr>
</table>
<% if user.id == current_user.id %>
<div class="row">
	<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>
<% end %>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

<!-- エラーメッセージ表示-->
<% if @user.errors.any? %>
	<h3><%= @user.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<!-- エラーメッセージ表示-->

<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit %>
</div>

<% end %>

app/views/users/index.html.erb
<div class="row">
	<div class="col-xs-3">
<h2>User info</h2>
<%= render 'users/profile', user: current_user %>
<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

<h2>New book</h2>
<%= render 'books/newform', book: @book %>
</div>
<div class="col-xs-9">
<h2>Users</h2>
<!--users一覧 -->
<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="4"></th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
			<td><%= user.name%></td>

			<% user ||= current_user %>
		<div class="stats">
			<th>following
				<a href="<%= following_user_path(user) %>">
    				<strong id="following" class="stat">
      					<%= user.following.count %>
    				</strong>
  				</a>
  			</th>
  			<th>followers
				<a href="<%= followers_user_path(user) %>">
    				<strong id="followers" class="stat">
      					<%= user.followers.count %>
    				</strong>
  				</a>
  			</th>
  		</div>
  			<th>
				<% unless  user.id == current_user.id  %>
				<div id="follow_form">
  					<% if current_user.following?(user) %>
    						<%= form_for(current_user.active_relationships.find_by(followed_id: user.id),html: { method: :delete }) do |f| %>
  							<%= f.submit "フォロー外す", class: "btn btn-primary" %>
						<% end %>
  						<% else %>
   							 <%= form_for(current_user.active_relationships.build) do |f| %>
  								<div><%= hidden_field_tag :followed_id, user.id %></div>
  								<%= f.submit "フォローする", class: "btn btn-primary" %>
							<% end %>
  						<% end %>
  					
  				</div>
				<% end %>
				</th>
			<th><%= link_to "Show", user, class: "user_#{user.id}" %></th>





			
		</tr>
		<% end %>
	</tbody>
</table>
</div>
</div>
<!--users一覧 -->

app/views/users/show.html.erb
<div class="row">
	<div class="col-xs-3">
<h2>User info</h2>
<%= render 'users/profile', user: @user %>


<% unless  @user.id == current_user.id  %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "フォロー外す", class: "btn btn-primary" %>
<% end %>
  <% else %>
    <%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォローする", class: "btn btn-primary" %>
<% end %>
  <% end %>
  </div>
<% end %>

<!--同コントローラーのviewで表示ならusersは省略可 -->



<h2>New book</h2>
<%= render 'books/newform', book: @book %>
</div>
<div class="col-xs-9">
<h2>Books</h2>
<!--books一覧 -->
<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th></th>
			<th>Title</th>
			<th>Opinion</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @books.each do |book| %>
		<tr>
			<td>
				<%= link_to do %>
				<%= attachment_image_tag(@user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
				<% end %>
			</td>
			<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
			<td><%= book.body %></td>
			<td style="text-align: center;">
						<div class="glyphicon glyphicon-comment"></div>
						<a href="#comments"><%= book.book_comments.count %></a>
					</td>
		</tr>
		<% end %>
	</tbody>
</table>
</div>
</div>
<!--books一覧 -->

app/views/users/show_follow.html.erb
        <div class="user_avatars">
          <table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
        <% @users.each do |user| %>
    <tr>
      <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
      <td><%= user.name%></td>
      <% user ||= current_user %>
    <div class="stats">
      <th>フォロー数
      <a href="<%= following_user_path(user) %>">
            <strong id="following" class="stat">
                <%= user.following.count %>
            </strong>
          </a>
        </th>
          <th>フォロワー数
      <a href="<%= followers_user_path(user) %>">
            <strong id="followers" class="stat">
                <%= user.followers.count %>
            </strong>
          </a></th>
      </div>
      <th>
        <% unless  user.id == current_user.id  %>
        <div id="follow_form">
            <% if current_user.following?(user) %>
                <%= form_for(current_user.active_relationships.find_by(followed_id: user.id),html: { method: :delete }) do |f| %>
                <%= f.submit "Unfollow", class: "btn btn-primary" %>
            <% end %>
              <% else %>
                 <%= form_for(current_user.active_relationships.build) do |f| %>
                  <div><%= hidden_field_tag :followed_id, user.id %></div>
                  <%= f.submit "Follow", class: "btn btn-primary" %>
              <% end %>
              <% end %>
            
          </div>
        <% end %>
        </th>
      <td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
    </tr>
    <% end %>
  </tbody>
</table>
  </div>
</div>